add Ruby version requirement
pi@raspberrypi ~ $ gem install soracom-1.0.3.gem
Building native extensions.  This could take a while...
ERROR:  Error installing soracom-1.0.3.gem:
	soracom requires Ruby version ~> 2.0.